services:
  # Database
  db:
    image: postgres:15-alpine
    container_name: bookworm-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bookworm_localhost-2025_04_24_18_57_48-dump.sql:/docker-entrypoint-initdb.d/bookworm_localhost-2025_04_24_18_57_48-dump.sql
      - ./init-simple.sh:/docker-entrypoint-initdb.d/init-simple.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build: ./backend
    container_name: bookworm-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bookworm
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build: ./frontend
    container_name: bookworm-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL=/api
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:
